# How to use GPU

In [1]:
import torch
import torch.nn as nn

## Convert to CUDA tensor: cuda()

In [2]:
x = torch.cuda.FloatTensor(2, 2)

x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [3]:
x = torch.FloatTensor(2, 2)

x

tensor([[2.3227e+24, 4.5227e-41],
        [2.3227e+24, 4.5227e-41]])

In [4]:
x.cuda()

tensor([[2.3227e+24, 4.5227e-41],
        [2.3227e+24, 4.5227e-41]], device='cuda:0')

In [5]:
d = torch.device('cuda:0')

In [6]:
x.cuda(device=d)

tensor([[2.3227e+24, 4.5227e-41],
        [2.3227e+24, 4.5227e-41]], device='cuda:0')

In [7]:
x.device

device(type='cpu')

## Convert to CUDA tensor: to()

In [8]:
x.to(device=d)

tensor([[2.3227e+24, 4.5227e-41],
        [2.3227e+24, 4.5227e-41]], device='cuda:0')

## Convert to CPU tensor from CUDA tensor

In [9]:
x = torch.cuda.FloatTensor(2, 2)

In [10]:
x = x.cpu()

In [11]:
d = torch.device('cpu')
x = x.to(d)

## Move model from CPU to GPU.

In [12]:
def print_params(model):
    for p in model.parameters():
        print(p)

In [13]:
linear = nn.Linear(2, 2)

print_params(linear)

Parameter containing:
tensor([[ 0.3533, -0.5705],
        [-0.2135, -0.3413]], requires_grad=True)
Parameter containing:
tensor([-0.4877, -0.3480], requires_grad=True)


In [14]:
linear = linear.cuda()

print_params(linear)

Parameter containing:
tensor([[ 0.3533, -0.5705],
        [-0.2135, -0.3413]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.4877, -0.3480], device='cuda:0', requires_grad=True)


In [15]:
linear = linear.cpu()

print_params(linear)

Parameter containing:
tensor([[ 0.3533, -0.5705],
        [-0.2135, -0.3413]], requires_grad=True)
Parameter containing:
tensor([-0.4877, -0.3480], requires_grad=True)


In [16]:
d = torch.device('cuda:0')
linear = linear.to(d)

print_params(linear)

Parameter containing:
tensor([[ 0.3533, -0.5705],
        [-0.2135, -0.3413]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.4877, -0.3480], device='cuda:0', requires_grad=True)


Note that nn.Module class does not have 'device' property.

In [18]:
linear.device


AttributeError: ignored

## Tricks

In [19]:
x = torch.cuda.FloatTensor(2, 2)

In [20]:
x.new(2, 2)

tensor([[-3.6893e+19,  1.6740e+00],
        [ 2.1350e-01,  3.4125e-01]], device='cuda:0')

In [21]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [22]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [23]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')