아래 문제들은 결과 출력까지 실행 후 ipynb  파일과 .py 파일로 제출  
print(b)의 결과가 다음과 같이 되는 code를 작성하시오..  
b는 a를 이용하여 정의 함.   최대한 다양한 연산을 사용할것.  
 , 유무는 신경 쓰지 말것

#학번 :   202347020
#이름 : 김대현

1.   
 [  [ [ 1.],   
        [ 2.],  
      [ 3.],  
      [ 4.] ]  
    [ [ 5.],  
      [ 6.],  
      [ 7.],  
      [ 8.] ],  
    [ [ 9.],  
      [10.],  
      [11.],  
      [12.] ]  ]  


In [8]:
import torch
a = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

b= a.reshape(12,1)

print(a)
print(b)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]])


2.  [ [[2., 2.],   
       [3., 4.]],  
       [[5., 6.],  
       [2., 8.]],  
      [[9., 2.],  
       [2., 2.]]  ]  

In [9]:
import torch
a = torch.tensor([[[ 2.,  2.,  3.,  4.]],
        [[ 5.,  6.,  2.,  8.]],
        [[ 9., 2, 2., 2.]]])
b= a.reshape(3,2,2)

print(a)
print(b)

tensor([[[2., 2., 3., 4.]],

        [[5., 6., 2., 8.]],

        [[9., 2., 2., 2.]]])
tensor([[[2., 2.],
         [3., 4.]],

        [[5., 6.],
         [2., 8.]],

        [[9., 2.],
         [2., 2.]]])


3.[[2., 2., 2., 5.],  
        [5., 5., 2., 5.],  
        [9., 5., 5., 2.]]  

In [12]:
import torch
a = torch.tensor([[[ 2.,  2.,  2.,  5.]],
        [[ 5.,  5,  2.,  5.]],
        [[ 9.,5, 5., 2.]]])
b= a.reshape(3,4)
print(a)
print(b)

tensor([[[2., 2., 2., 5.]],

        [[5., 5., 2., 5.]],

        [[9., 5., 5., 2.]]])
tensor([[2., 2., 2., 5.],
        [5., 5., 2., 5.],
        [9., 5., 5., 2.]])


4.

[[[1., 2., 2.]],  
   [[3., 4., 4.]]]

In [13]:
import torch
a = torch.FloatTensor([[1, 2 ,2],
                       [3, 4, 4]])
b= a.reshape(2,1,3)

print(a)
print(b)
print(b.size())

tensor([[1., 2., 2.],
        [3., 4., 4.]])
tensor([[[1., 2., 2.]],

        [[3., 4., 4.]]])
torch.Size([2, 1, 3])


5. [[5., 6., 1.],  
     [7., 8., 1.]]



In [15]:
import torch
a = torch.FloatTensor([
                       [[1, 2,1],
                        [3, 4,1]],

                       [[5, 6,1],
                        [7, 8,1]],

                       [[9, 10,1],
                        [11, 12,1]]])
b= a[1].reshape(2,3)


print(a)
print(b)
print(b.size())

tensor([[[ 1.,  2.,  1.],
         [ 3.,  4.,  1.]],

        [[ 5.,  6.,  1.],
         [ 7.,  8.,  1.]],

        [[ 9., 10.,  1.],
         [11., 12.,  1.]]])
tensor([[5., 6., 1.],
        [7., 8., 1.]])
torch.Size([2, 3])


  6.  [[1., 1.],  
     [1., 1.],  
     [1., 1.]]  

In [17]:
import torch
a = torch.FloatTensor([
                       [[1, 2,1],
                        [3, 4,1]],

                       [[5, 6,1],
                        [7, 8,1]],

                       [[9, 10,1],
                        [11, 12,1]]])
b= a[:,:,2]


print(a)
print(b)
print(b.size())

tensor([[[ 1.,  2.,  1.],
         [ 3.,  4.,  1.]],

        [[ 5.,  6.,  1.],
         [ 7.,  8.,  1.]],

        [[ 9., 10.,  1.],
         [11., 12.,  1.]]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
torch.Size([3, 2])


7. [    [ 2.],  
     [ 6.],  
     [10.]  ]

In [19]:
import torch
a = torch.FloatTensor([
                       [[1, 2,1],
                        [3, 4,1]],

                       [[5, 6,1],
                        [7, 8,1]],

                       [[9, 10,1],
                        [11, 12,1]]])
b= a[:,0,1].reshape(3,1)

print(a)
print(b)
print(b.size())

tensor([[[ 1.,  2.,  1.],
         [ 3.,  4.,  1.]],

        [[ 5.,  6.,  1.],
         [ 7.,  8.,  1.]],

        [[ 9., 10.,  1.],
         [11., 12.,  1.]]])
tensor([[ 2.],
        [ 6.],
        [10.]])
torch.Size([3, 1])


8. [[ 1.,  3., 10., 12.],  
      [ 4.,  6., 13., 15.],  
      [ 7.,  9., 16., 18.]]  

In [20]:
import torch
a1 =  torch.FloatTensor([[1,  3],
                       [4,  6],
                       [7,  9]])
a2 = torch.FloatTensor([[10,  12],
                       [13,  15],
                       [16,  18]])
b= torch.cat([a1,a2],dim = -1)


print(b)
print(b.size())

tensor([[ 1.,  3., 10., 12.],
        [ 4.,  6., 13., 15.],
        [ 7.,  9., 16., 18.]])
torch.Size([3, 4])


  9.     [[[ 1.,  2.],  
         [ 3.,  4.],  
         [ 5.,  6.]],  
        [[10., 11.],  
         [12., 13.],  
         [14., 15.]]]   

In [21]:
import torch
a1 =  torch.FloatTensor([[1,  2],
                       [3,  4],
                       [5,  6]])
a2 = torch.FloatTensor([[10,  11],
                       [12,  13],
                       [14,  15]])
b= torch.cat([a1,a2],dim = 0)
print(b)
print(b.size())

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [10., 11.],
        [12., 13.],
        [14., 15.]])
torch.Size([6, 2])


10.   [[[1., 2., 3.],  
         [1., 2., 3.],  
         [1., 2., 3.],  
         [1., 2., 3.]],  

        [[4., 5., 6.],  
         [4., 5., 6.],  
         [4., 5., 6.],  
         [4., 5., 6.]]]  

In [33]:
import torch
a = torch.FloatTensor([[[1, 2, 3]],
                       [[4, 5, 6]]])
print(a.size)
b= a.expand(2,4,3)
print(b)
print(b.size())

<built-in method size of Tensor object at 0x7bf1fe4a5b20>
tensor([[[1., 2., 3.],
         [1., 2., 3.],
         [1., 2., 3.],
         [1., 2., 3.]],

        [[4., 5., 6.],
         [4., 5., 6.],
         [4., 5., 6.],
         [4., 5., 6.]]])
torch.Size([2, 4, 3])


11.[[1, 2],  
          [0, 2],  
          [1, 2]]  

In [39]:
import torch
a = torch.FloatTensor([
                       [[1, 2,1],
                        [3, 4,7]],

                       [[9, 6,1],
                        [9, 8,15]],

                       [[9, 10,1],
                        [13, 12,17]]])

print(a.size())
b= a.argmax(dim = -1)
print(b)

torch.Size([3, 2, 3])
tensor([[1, 2],
        [0, 2],
        [1, 2]])


12. [[[ 1.,  2.,  1.],  
       [ 3.,  4.,  7.]],  
      [[ 9.,  6.,  1.],  
      [ 9.,  8., -1.]],  
      [[ 9., -1.,  1.],  
       [-1., -1., -1.]]]  

In [37]:
import torch
a = torch.FloatTensor([
                       [[1, 2,1],
                        [3, 4,7]],
                       [[9, 6,1],
                        [9, 8,15]],
                       [[9, 10,1],
                        [13, 12,17]]])

print(a.size())

mask = a >= 10
b= a.masked_fill(mask,value = -1)
print(b)

torch.Size([3, 2, 3])
tensor([[[ 1.,  2.,  1.],
         [ 3.,  4.,  7.]],

        [[ 9.,  6.,  1.],
         [ 9.,  8., -1.]],

        [[ 9., -1.,  1.],
         [-1., -1., -1.]]])
